package io.github.katarem.piratify.entities

import io.github.katarem.piratify.R

object Canciones{
    val Maquiavelico = Cancion("Maquiavélico", R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.maquiavelico_canserbero,"4:44")
    val CestLaMort = Cancion("C'est La Mort",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.cest_la_mort_canserbero,"7:39")
    val EsEpico = Cancion("Es Épico",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.es_epico_canserbero,"6:01")
    val SerVero = Cancion("Ser Vero",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.ser_vero_canserbero,"3:38")
    val EnElValleDeLasSombras = Cancion("En el Valle de las Sombras",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.en_el_valle_de_las_sombras_canserbero,"5:40")
    val MundoDePiedra = Cancion("Mundo de Piedra",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.mundo_de_piedra_canserbero,"4:44")
    val SinMercy = Cancion("Sin Mercy",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.sin_mercy_canserbero,"3:22")
    val UnDiaEnElBarrio = Cancion("Un Día en el Barrio",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.un_dia_en_el_barrio_canserbero,"6:19")
    val Llovia = Cancion("Llovía",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.llovia_canserbero,"4:52")
    val YEnUnEspejoVi = Cancion("Y en un Espejo Vi",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.y_en_un_espejo_vi_canserbero,"4:18")
    val LaHoraDelJuicio = Cancion("La Hora del Juicio",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.la_hora_del_juicio_canserbero,"3:52")
    val ElPrimerTrago = Cancion("El Primer Trago",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.el_primer_trago_canserbero,"6:22")
    val DeMiMuerte = Cancion("De Mi Muerte",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.de_mi_muerte_canserbero,"3:41")
    val Jeremias17 = Cancion("Jeremías 17-5",R.drawable.muerte_canserbero,"Canserbero","Muerte",R.raw.jeremias_17_canserbero,"5:18")
    val TheRootOfAllEvil = Cancion("The Root of All Evil",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.the_root_of_all_evil_dreamtheater,"8:25")
    val TheAnswerLiesWithin = Cancion("The Answer Lies Within",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.the_answer_lies_within_dreamtheater,"5:33")
    val TheseWalls = Cancion("These Walls",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.the_answer_lies_within_dreamtheater,"7:36")
    val IWalkBesideYou = Cancion("I Walk Beside You",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.these_walls_dreamtheater,"4:29")
    val PanicAttack = Cancion("Panic Attack",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.panic_attack_dreamtheater,"8:13")
    val NeverEnough = Cancion("Never Enough",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.never_enough_dreamtheater,"6:46")
    val SacrifiedSons = Cancion("Sacrified Sons",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.sacrified_sons_dreamtheater,"10:42")
    val Octavarium = Cancion("Octavarium",R.drawable.octavarium,"Dream Theater","Octavarium",R.raw.octavarium_dreamtheater,"24:00")
    val RipAndTear = Cancion("Rip & Tear",R.drawable.doom_album,"Doomguy","Doom OST",R.raw.rip_and_tear_doom,"4:17")
    val ElArteSano = Cancion("El Arte Sano",R.drawable.keyblade,"Keyblade","",R.raw.el_arte_sano_keyblade,"5:36")
    val ElViolador = Cancion("El Violador",R.drawable.piterg,"Piter G","",R.raw.el_violador_piterg,"3:18")
    val Maw = Cancion("Maw",R.drawable.maw,"Gato","miau",R.raw.maw_master,"0:10")
    val Nightmare = Cancion("Nightmare",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.nightmare_avengedsevenfold,"6:14")
    val WelcomeToTheFamily = Cancion("Welcome To The Family",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.welcome_to_the_family_avengedsevenfold,"4:05")
    val DangerLine = Cancion("Danger Line",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.danger_line_avengedsevenfold,"5:28")
    val BuriedAlive = Cancion("Buried Alive",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.buried_alive_avengedsevenfold,"6:44")
    val NaturalBornKiller = Cancion("Natural Born Killer",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.natural_born_killer_avengedsevenfold,"5:15")
    val SoFarAway = Cancion("So Far Away",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.so_far_away_avengedsevenfold,"5:26")
    val GodHatesUs = Cancion("God Hates Us",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.god_hates_us_avengedsevenfold,"5:19")
    val Victim = Cancion("Victim",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.victim_avengedsevenfold,"7:29")
    val TonightTheWorldDies = Cancion("Tonight The World Dies",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.tonight_the_world_dies_avengedsevenfold,"4:41")
    val Fiction = Cancion("Fiction",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.fiction_avengedsevenfold,"5:07")
    val SaveMe = Cancion("Save Me",R.drawable.nightmare,"Avenged Sevenfold","Nightmare",R.raw.save_me_avengedsevenfold,"10:56")
    val Abrazate = Cancion("Abrázate",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.abrazate_nach,"4:27")
    val Leyenda = Cancion("Leyenda",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.leyenda_nach,"3:19")
    val ElHipHopQueSe = Cancion("El Hip-Hop Que Sé",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.el_hip_hop_que_se_nach,"4:11")
    val AdiosEspania = Cancion("Adiós España",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.adios_espania_nach,"3:45")
    val TantasRazones = Cancion("Tantas Razones",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.tantas_razones_nach,"2:59")
    val Urbanologia = Cancion("Urbanología",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.urbanologia_nach,"8:05")
    val Anticuerpos = Cancion("Anticuerpos",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.anticuerpos_nach,"3:30")
    val Ahora = Cancion("Ahora",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.ahora_nach,"4:50")
    val Gratis = Cancion("Gratis",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.gratis_nach,"4:14")
    val EntreElPlacerYElDolor = Cancion("Entre El Placer Y El Dolor",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.entre_el_placer_y_el_dolor_nach,"4:51")
    val RapEspaniol = Cancion("Rap Español",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.rap_espaniol_nach,"4:23")
    val TalComoEres = Cancion("Tal Como Eres",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.tal_como_eres_nach,"4:17")
    val EllosyYo = Cancion("Ellos Y Yo",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.ellos_y_yo_nach,"3:39")
    val PoesiaDeGuerra = Cancion("Poesía De Guerra",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.poesia_de_guerra_nach,"4:56")
    val Viviendo = Cancion("Viviendo",R.drawable.atravesdemi,"Nach","A Través de Mí",R.raw.viviendo_nach,"5:14")
}